### ISSUE TITLE
improve UI/UX of  app

### ISSUE THREAD

**Issue by doomers** [doomers/BluetoothConnectivity#1]
currently, the UI/UX of the app is not good enough 
suggest some innovative ways to improve it, and make a PR for it.

**Comment by webianks** [comment]
I will fix the UI and soon make a PR.

**Comment by pingrishabh** [comment]
I fixed the UI/UX. Made it look aesthetic and more appealing. Do check the PR, review, recommend changes if any. #8

**Comment by pingrishabh** [comment]
Here's how it looks right now. Feel free to recommend any changes.

![screenshot](https://user-images.githubusercontent.com/22350239/32141540-2f9aff6e-bca9-11e7-9e87-fc1032aa9644.jpg)

**Comment by doomers** [comment]
Thanks for the great work @Cheesetouched

**Comment by pingrishabh** [comment]
Not a problem. @doomers You can close this issue now.

**Comment by doomers** [comment]
Sure
